test_pickle_exception: even harder location stripping. Ref #74.
With Python 3.13, we need to strip even harder, because we get
location lines with differing amounts of tildes and up carets in
them, e.g.:

    ~~^~~~~

and:

    ^^^^^^^

Let's ditch the regex and instead go line-by-line with a pretty
loose match for anything that looks like a location line.

Signed-off-by: Adam Williamson <awilliam@redhat.com>